vich_uploader:
    db_driver: orm # Vous pouvez utiliser d'autres drivers si nécessaire
    mappings:
        images:
            uri_prefix: uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
